version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_mvc_db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    # Wait for MySQL service before starting Flask app
    command: ["./wait-for-it.sh", "db", "3306", "--", "python", "run.py"]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASSWORD: flaskpassword
      DB_NAME: flask_mvc_db
    depends_on:
      - db

volumes:
  db_data:
