apiVersion: v1
kind: Service
metadata:
  name: mysql  # Internal service name used by Flask app
spec:
  ports:
  - port: 3306  # Expose MySQL port inside the cluster
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # Enables direct pod-to-pod communication (optional)
